Models/ErrorViewModel.cs
using System;

namespace aprintist.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ObservationContext.cs
using Microsoft.EntityFrameworkCore;

namespace aprintist.Models
{
    public class ObservationContext : DbContext
    {
        public ObservationContext (DbContextOptions<ObservationContext> options)
            : base(options)
        {
        }

        public DbSet<aprintist.Models.Observation> Movie { get; set; }
    }
}

Models/ObservationViewModel.cs
using System;

namespace aprintist.Models
{
    public class Observation
    {
        public int ID { get; set; }
        public string Slicer { get; set; }
        public string Printer { get; set; }
        public TimeSpan Estimate { get; set; }
        public TimeSpan Actual { get; set; }
        
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using aprintist.Models;

namespace aprintist.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ObservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using aprintist.Models;

namespace aprintist.Controllers
{
    public class ObservationsController : Controller
    {
        private readonly ObservationContext _context;

        public ObservationsController(ObservationContext context)
        {
            _context = context;
        }

        // GET: Observations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Movie.ToListAsync());
        }

        // GET: Observations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var observation = await _context.Movie
                .SingleOrDefaultAsync(m => m.ID == id);
            if (observation == null)
            {
                return NotFound();
            }

            return View(observation);
        }

        // GET: Observations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Observations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Slicer,Printer,Estimate,Actual")] Observation observation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(observation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(observation);
        }

        // GET: Observations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var observation = await _context.Movie.SingleOrDefaultAsync(m => m.ID == id);
            if (observation == null)
            {
                return NotFound();
            }
            return View(observation);
        }

        // POST: Observations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Slicer,Printer,Estimate,Actual")] Observation observation)
        {
            if (id != observation.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(observation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ObservationExists(observation.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(observation);
        }

        // GET: Observations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var observation = await _context.Movie
                .SingleOrDefaultAsync(m => m.ID == id);
            if (observation == null)
            {
                return NotFound();
            }

            return View(observation);
        }

        // POST: Observations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var observation = await _context.Movie.SingleOrDefaultAsync(m => m.ID == id);
            _context.Movie.Remove(observation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ObservationExists(int id)
        {
            return _context.Movie.Any(e => e.ID == id);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "Print time estimator";
}
<h2>Print time Estimator</h2>

<p>aprintrist... Print Time Estimator... This is a tool to map the relationship between actual print times and estimated print times.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>Contact</h2>
<p><a href="https://github.com/buildcomplete/aprintist" target="_blank">https://github.com/buildcomplete/aprintist</a></p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

Views/Observations/Create.cshtml
@model aprintist.Models.Observation

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Observation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Slicer" class="control-label"></label>
                <input asp-for="Slicer" class="form-control" />
                <span asp-validation-for="Slicer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Printer" class="control-label"></label>
                <input asp-for="Printer" class="form-control" />
                <span asp-validation-for="Printer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estimate" class="control-label"></label>
                <input asp-for="Estimate" class="form-control" />
                <span asp-validation-for="Estimate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Actual" class="control-label"></label>
                <input asp-for="Actual" class="form-control" />
                <span asp-validation-for="Actual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Observations/Delete.cshtml
@model aprintist.Models.Observation

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Observation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Slicer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Slicer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Printer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Printer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Estimate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Estimate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Actual)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Actual)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Observations/Details.cshtml
@model aprintist.Models.Observation

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Observation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Slicer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Slicer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Printer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Printer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Estimate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Estimate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Actual)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Actual)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Observations/Edit.cshtml
@model aprintist.Models.Observation

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Observation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Slicer" class="control-label"></label>
                <input asp-for="Slicer" class="form-control" />
                <span asp-validation-for="Slicer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Printer" class="control-label"></label>
                <input asp-for="Printer" class="form-control" />
                <span asp-validation-for="Printer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estimate" class="control-label"></label>
                <input asp-for="Estimate" class="form-control" />
                <span asp-validation-for="Estimate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Actual" class="control-label"></label>
                <input asp-for="Actual" class="form-control" />
                <span asp-validation-for="Actual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Observations/Index.cshtml
@model IEnumerable<aprintist.Models.Observation>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Slicer)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Printer)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Estimate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Actual)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Slicer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Printer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estimate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Actual)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - aPrintist</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">aprintist</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Observations" asp-action="Index">Observations</a></li>                    
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p><span style="display:inline-block; transform: rotateY(180deg);">&copy;</span> 2017 - aprintist</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>